export const ADVERTISED_OFFER = 'ADVERTISED_OFFER';
export const POPULATE_ADVERTISED_OFFER = 'POPULATE_ADVERTISED_OFFER';
export const TODAY_OFFER = 'TODAY_OFFER';
export const TODAY_OFFER_PAYLOAD = 'TODAY_OFFER_PAYLOAD';

